name: 'generate_embeddings'
on: # run on master branch changes
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/supabase-embeddings-generator@v0.0.5
        with:
          supabase-url: 'https://utnyrxbtlxwxsbipqpju.supabase.co'
          supabase-service-role-key: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          openai-key: ${{ secrets.OPENAI_KEY }}
          docs-root-path: 'docs'
